# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LinkedPipes ETL
email: klimek@opendata.cz
description: > # this means to ignore newlines until "baseurl:"
  Web presentation of LinkedPipes, a suite of open-source software for Linked Data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://etl.linkedpipes.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  linkedpipes
#highlighter: pygments

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
sass:
    sass_dir: _sass
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap